django_pjt4/django_pjt4/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('movies/',include('movies.urls')),
    path('reviews/',include('reviews.urls')),
]

django_pjt4/movies/urls.py
from django.urls import path
from . import views
app_name = "movies"
urlpatterns = [
    path('',views.index,name="index"),
    path('create/',views.create,name="create"),
    path('<int:movie_id>/',views.detail,name="detail"),
    path('<int:movie_id>/update/',views.update,name="update"),
    path('<int:movie_id>/delete/',views.delete,name ="delete"),


    ]

django_pjt4/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length = 100)
    poster = models.CharField(max_length = 200)
    def __str__(self):
        return '%s' % (self.title)

django_pjt4/movies/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    title = forms.CharField(
            label='제목',
            help_text='',
            widget=forms.TextInput(
                    attrs={
                        'class': 'w-100 ',
                        'placeholder': '제목 입력'
                    }
                )
        )
    # poster = forms.CharField(
    #         label='poster',
    #         help_text='',
    #         widget=forms.TextInput(
    #                 attrs={
    #                     'class': 'w-100 ',
    #                     'placeholder': 'url을 입력해주세요'
    #                 }
    #             )
    #     )
    class Meta:
        model = Movie
        fields = ['title']

django_pjt4/movies/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import MovieForm
from .models import Movie
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import requests
import json

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies':movies
    }
    return render(request,'movies/index.html',context)

@login_required
def create(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = MovieForm(request.POST)
            if form.is_valid():
                movie=form.save(commit=False)
                url = f'https://api.themoviedb.org/3/search/movie?api_key=69570904cbfa7d422a8a753a576d8c32&language=ko-KR&query={movie.title}&page=1&include_adult=false2'
                res= requests.get(url)
                js =  json.loads(res.text)
                re = js['results'][0]['poster_path']
                movie.poster = f'https://image.tmdb.org/t/p/w300{re}'
                movie.save()
                return redirect('movies:index')
        else:
            form = MovieForm()
        context ={
            'form':form
        }
        return render(request,'movies/form.html',context)
    else:
        messages.warning(request,'잘못된 접근입니다.')
        return redirect('movies:index')


def detail(request,movie_id):
    movie = get_object_or_404(Movie,id=movie_id)
    context ={
        'movie':movie
    }
    return render(request,'movies/detail.html',context)


def update(request,movie_id):
    movie = get_object_or_404(Movie,id=movie_id)
    if request.user.is_superuser:
        if request.method == 'POST':
            form = MovieForm(request.POST,instance = movie)
            if form.is_valid():
                review=form.save()
                return redirect('movies:detail',movie.id)

        else:
            form = MovieForm(instance = movie)
        context = {
            'form':form
        }
        return render(request,'movies/form.html',context)
    else:
        messages.warning(request,'잘못된 접근입니다.')
        return redirect('movies:index')


def delete(request,movie_id):
    if request.user.is_superuser:
        movie = get_object_or_404(Movie,id=movie_id)
        movie.delete()
        return redirect('movies:index')
    else:
        messages.warning(request,'잘못된 접근입니다.')
        return redirect('movies:index')

django_pjt4/movies/templates/movies/detail.html
{% extends 'base.html' %}


{% block content %}
    <div class="text-center h1 col-6 offset-3 mt-5 mb-5" style="border-bottom: 2px solid">영화 리뷰 게시판</div>
    <div class="row justify-content-center border">
    <div class="h4 text-center border-bottom col-8 offset-2 my-5 mx-0 px-0">{{ movie.title }}</div>
    <img src="{{ movie.poster }}" class="col-6" alt="">
    <div class="col-12 my-5"></div>
    {% if user.is_superuser %}
        <a href="{% url 'movies:update' movie.id %}" class="mx-5"> 수정</a>
        <a href="{% url 'movies:delete' movie.id %}">삭제</a>
    {% endif %}
    <div class="pb-5"></div>
    </div>
{% endblock %}

django_pjt4/movies/templates/movies/form.html
{% extends 'base.html' %}




{% block content %}
{% if request.resolver_match.url_name == 'create' %}
    <p  class="my-5 text-center h1">새 영화 등록</p>
{% else %}
    <p  class="my-5 text-center h1">영화 수정</p>
{% endif %}


    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button> 제출</button>
    </form>


{% endblock %}

django_pjt4/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center h1 col-6 offset-3 mt-5 mb-5" style="border-bottom: 2px solid">영화 게시판</div>
    <table class="table mx-auto table-bordered mt-5">
  <thead class="thead-light">
    <tr>
      <th scope="col" class="text-center">번호</th>
      <th scope="col" class="text-center">영화제목</th>
    </tr>
  </thead>
  <tbody>

    {% for movie in movies %}
        <tr>
          <th scope="row" class="text-center">{{ forloop.revcounter }}</th>

          <td><a href="{% url 'movies:detail' movie.id %}" class="text-dark text-decoration-none ">{{ movie.title }}</a></td>

        </tr>

    {% endfor %}
      </tbody>
</table>

           {% if user.is_superuser %}
        <a href="{% url 'movies:create' %}">새 영화 등록</a>
        {% endif %}
{% endblock %}