django_pjt4/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns=[
    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('<username>/',views.profile,name='profile'),
    path('<username>/follow/',views.follow,name='follow')
    ]

django_pjt4/django_pjt4/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('movies/',include('movies.urls')),
    path('reviews/',include('reviews.urls')),
]

django_pjt4/movies/urls.py
from django.urls import path
from . import views
app_name = "movies"
urlpatterns = [
    path('',views.index,name="index"),
    path('create/',views.create,name="create"),
    path('<int:movie_id>/',views.detail,name="detail"),
    path('<int:movie_id>/update/',views.update,name="update"),
    path('<int:movie_id>/delete/',views.delete,name ="delete"),


    ]

django_pjt4/reviews/urls.py
from django.urls import path
from . import views

app_name='reviews'



urlpatterns=[
    path('',views.index,name='index'),
    path('create/',views.create,name='review_create'),
    path('<int:review_id>/',views.review_detail,name='review_detail'),
    path('<int:review_id>/delete/',views.review_delete,name='review_delete'),
    path('<int:review_id>/update/',views.review_update,name='review_update'),
    path('<int:review_id>/like/',views.like,name='like'),
    path('<int:review_id>/comments/',views.comments_create,name='comments_create'),
    path('<int:review_id>/comments/<int:comment_id>/delete',views.comments_delete,name='comments_delete'),
    path('movie-autocomp/',views.MovieAutocomp.as_view(),name = 'movie-autocomp')
    ]

django_pjt4/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>


    <nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark">
      <a class="navbar-brand" href="{% url 'reviews:index' %}">
        <img class="img-fluid"src="{% static "images/logo.png" %}" width="100"height="80">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarsExample04" style>
        <ul class="navbar-nav list-unstyled mb-0 ">
        <!-- 여기에 리뷰게시판 들어가는거 추가하기 !!!-->
       {% if request.user.is_authenticated %}
            <li class="nav-item mx-3 my-2 h5 text-center py-2 text-primary "> {{ request.user.username }}님 안녕하세요 </li>
            <li class="nav-item mx-3 my-2 "><a href="{% url 'accounts:logout' %}" class="nav-link" >로그아웃</a></li>
        {% else %}
            <li class="nav-item mx-3 my-2 "><a href="{% url 'accounts:signup' %}"  class="nav-link">회원가입</a></li>
            <li class="nav-item mx-3 my-2 "><a href="{% url 'accounts:login' %}"  class="nav-link">로그인</a></li>
        {% endif %}

        </ul>
      </div>
  </nav>
      {% if messages %}
    <ul class="messages list-unstyled ">
        {% for message in messages %}
        <li{% if message.tags %} class="bg-{{ message.tags }} px-5 py-3 h3 "{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
  <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>