django_pjt5/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout')
]

django_pjt5/django_pjt5/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
    path('accounts/',include('accounts.urls'))
]

django_pjt5/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'


urlpatterns =[
    path('',views.index,name="index"),
    path('<int:movie_id>/like/',views.like,name="like"),
    path('recommand/',views.recommand,name="recommand"),
    path('recommand/<int:genre_id>/',views.recommand_genre,name="recommand_genre"),
    path('recommand/genre_random/',views.recommand_genre_random,name="recommand_genre_random"),
    path('recommand/random/',views.recommand_random,name="recommand_random")
    
]

django_pjt5/accounts/models.py
from django.db import models
# Create your models here.

django_pjt5/movies/models.py
# Create your models here.
from django.db import models
from django.conf import settings


class Genre(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=300)
    original_title = models.CharField(max_length=300)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    adult = models.BooleanField()
    overview = models.TextField()
    original_language = models.CharField(max_length=10)
    poster_path = models.CharField(max_length=100)
    backdrop_path = models.CharField(max_length=100, default='')
    genres = models.ManyToManyField(Genre, related_name='movies')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')
    def __str__(self):
        return self.title

django_pjt5/movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['genres']
        widgets = {
            'genres':forms.CheckboxSelectMultiple(attrs={
                'class':'list-unstyled'
            })
        }

django_pjt5/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def index(request):
    User = get_user_model()
    users = User.objects.all()
    context={
        'users':users
    }
    return render(request,'accounts/index.html',context)

# Create your views here.
def signup(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect ('accounts:index')
        else:
            messages.warning(request,"다시 입력하세요")
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request,'accounts/signup.html',context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            auth_login(request,form.get_user())
            return redirect(request.GET.get('next') or 'accounts:index')
        else:
            messages.warning(request,'다시')
    else:
        form = AuthenticationForm()
    context={
        'form': form
    }
    return render(request,'accounts/login.html',context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

django_pjt5/movies/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Movie
from django.core.paginator import Paginator
from django.http import JsonResponse
from .models import Genre
import random
from .forms import MovieForm
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    paginator = Paginator(movies,12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    page_cnt = len(page_obj)%3
    context = {
        'movies':movies,
        'page_obj':page_obj,
        'page_cnt':page_cnt
        
    }

    return render(request,'movies/index.html',context)

def like(request,movie_id):
    user = request.user
    movie = get_object_or_404(Movie,id=movie_id)
    if movie.like_users.filter(id=user.id).exists():
        movie.like_users.remove(user)
        status = False
    else:
        movie.like_users.add(user)
        status = True

    context = {
        'status':status,
        'like_count': movie.like_users.count(),
    }

    return JsonResponse(context)

def recommand(request):
    if request.method == 'POST':
        a= request.POST
        genre_list = a.getlist('genres')
        movies = Movie.objects.filter(genres__in=genre_list).order_by('-popularity','-vote_average').distinct()[:10]
        context ={
            'movies':movies
        }
        return render(request,'movies/recommand_random.html',context)
    else:
        genres = Genre.objects.all()
        form = MovieForm()

        context = {
            'genres': genres,
            'form': form
        }
        return render(request,'movies/recommand.html',context)

def recommand_genre(request,genre_id):
    genre = Genre.objects.get(id=genre_id)
    movies = genre.movies.order_by('-vote_average').order_by('-popularity')[:10]
    context = {
        'movies':movies,
        'genre':genre
    }
    
    return render(request,'movies/recommand_genre.html',context) 



def recommand_genre_random(request):
    genres = list(Genre.objects.all().values('id'))
    genre_list=[]
    for genre in genres:
        genre_list.append(genre['id'])
    go_to = random.choice(genre_list)
    while True:
        genre = Genre.objects.get(id=go_to)
        movies = genre.movies.order_by('-vote_average').order_by('-popularity')[:10]
        if movies:
            break
        go_to = random.choice(genre_list)
    context={
        'movies':movies,
        'genre':genre
    }
    return render(request,'movies/recommand_genre.html',context) 

def recommand_random(request):
    movies_id = Movie.objects.all().values('id')
    movie_list=[]
    for movie in movies_id:
        movie_list.append(movie['id'])
    movie_choices = random.sample(movie_list,10)
    movies = []
    for movie_id in movie_choices:
        movies.append(Movie.objects.get(id=movie_id))
    context = {
        'movies':movies
    }
    return render(request,'movies/recommand_random.html',context)

django_pjt5/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}

{% block body %}
  <div class="text-center h1 col-6 mt-5 mb-5" style="border-bottom: 2px solid">영화 게시판</div>
  <div class="col-12"></div>
  {% for movie in page_obj %}

  <div class="col-sm-6 col-md-4 mb-3" >
    <div class="border mx-2 p-3">
        <img src="https://image.tmdb.org/t/p/w780/{{movie.poster_path}}" class="card-img-top p-1" width = "auto" height="400px">
        <div class="card-body" >
          <h6 class="card_text">{{movie.title}} </h6>
          <hr>
          <div class ="col-5  offset-7">평점 : {{ movie.vote_average }}</div>
          <div class="card-text"  ><p style="overflow: hidden;
          text-overflow: ellipsis;
          display:-webkit-box;
          -webkit-box-orient: vertical;
          -webkit-line-clamp: 5;
          word-wrap: break-word;
          line-height: 1.2em;
          height: 6em;

            ">{{movie.overview}}</p></div>
          <hr>
          {% if request.user in movie.like_users.all %}
          <div class="card_text" data-like="true" style="color:crimson; height: 16px;" data-id="{{movie.id}}"> ♥</div>
          <span id = "like-count-{{movie.id}}" >{{ movie.like_users.count }}</span>
          {% else %}
          <div class="card_text" data-like="ture"  style="color:black; height: 16px;"  data-id="{{movie.id}}"> ♡ </div>
          <span id = "like-count-{{movie.id}}" >{{ movie.like_users.count }}</span>
          {% endif %}
          <div style="font-size: 14px;">
            장르:
            {% for genre in movie.genres.all %}
            {% if forloop.counter < 4 %}
              {{ genre.name }}
            {% endif %}
            {% endfor %}
          </div>
        </div>
    </div>
  </div>
  {% endfor %}
  {% if page_cnt == 1 %}
    div.col-sm-6.col-md-4
    <div class="col-sm-6 col-md-4"></div>
    <div class="col-sm-6 col-md-4"></div>
  {% elif page_cnt == 2 %}
  <div class="col-sm-6 col-md-4"></div>
  {% endif %}
  
  <div class= "col-12"></div>



  <ul class= "col-4">{% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}</ul>
  <script>  
  const likeBtns = document.querySelectorAll('[data-like]')
  
  likeBtns.forEach((likeBtn)=>{
    likeBtn.addEventListener('click',function(event){
      const movieId = event.target.dataset.id
      const movieLikeCount = document.querySelector(`#like-count-${movieId}`)

      axios.get(`/movies/${movieId}/like/`)
      .then((response)=>{
        console.log(response.data)
        if (response.data.status){
          event.target.innerText = '♥'
          event.target.style.color = "crimson"
          movieLikeCount.innerHTML = response.data.like_count

        } else{
          event.target.innerText = '♡'
          event.target.style.color = "black"
          movieLikeCount.innerHTML = response.data.like_count
          

        }


      }

      )







    })





  })
  
  
  
  
  </script>
  <script>
    const imgBtns = document.querySelectorAll('img')
    console.log(imgBtns)
  


    imgBtns.forEach((imgBtn)=>{
      imgBtn.addEventListener('mouseover',function(event){
        event.target.style.transform = "scale(1.2)";
        event.target.style.zIndex = 1;
        event.target.style.transition = "all 0.5s";
      })
    })
    imgBtns.forEach((imgBtn)=>{
      imgBtn.addEventListener('mouseout',function(event){
        event.target.style.transform = "scale(1)";
        event.target.style.zIndex = 0;
        event.target.style.transition = "all 0.5s";
      })
    }
    )
  </script>
{% endblock %}

django_pjt5/movies/templates/movies/recommand.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}
{% block body %}
  <div class=""><h1> 추천 게시판</h1></div>
  <div class="w-100 my-5"></div>
  <li class = "dropdown" style="list-style:none;">
    <a class="dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      직접 장르를 선택하실래요
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
  {% for genre in genres %}
    <a class="dropdown-item"href="{% url 'movies:recommand_genre' genre.id %}">{{genre.name}}</a>
    
  {% endfor %}
</div>
</li>
<div class="w-100"></div>
<div class="mt-5"> <a href="{% url 'movies:recommand_genre_random' %}">아니면 랜덤하게 장르를 골라 보실래요.? </a></div>
<div class="w-100"></div>
<div class="mt-5"> <a href="{% url 'movies:recommand_random' %}">그냥 랜덤하게 골라 보실래요.? </a></div>
<div class="w-100"></div>
<div class="text-center mt-5"> 여러개를 골라보실래요.?
<form action="" method='POST'>
  {% csrf_token %}
  {{form|crispy}}
  <button>제출</button>
</form>
</div>
{% endblock %}

django_pjt5/movies/templates/movies/recommand_genre.html
{% extends 'base.html' %}


{% block body %}
<div class="text-center h1 col-6 mt-5 mb-5" style="border-bottom: 2px solid">{{genre.name}} 게시판</div>
<div class="w-100"></div>
{% for movie in movies %}

<div class="col-sm-6 col-md-4 mb-3" style="">
  <div class="border mx-2 p-3">
      <img src="https://image.tmdb.org/t/p/w780/{{movie.poster_path}}" class="card-img-top p-1" width = "auto" height="400px">
      <div class="card-body" >
        <h6 class="card_text">{{movie.title}} </h6>
        <hr>
        <div class ="col-5  offset-7">평점 : {{ movie.vote_average }}</div>
        <div class="card-text"  ><p style="overflow: hidden;
        text-overflow: ellipsis;
        display:-webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 5;
        word-wrap: break-word;
        line-height: 1.2em;
        height: 6em;

          ">{{movie.overview}}</p></div>
        <hr>
        {% if request.user in movie.like_users.all %}
        <div class="card_text" data-like="true" style="color:crimson; height: 16px;" data-id="{{movie.id}}"> ♥</div>
        <span id = "like-count-{{movie.id}}" >{{ movie.like_users.count }}</span>
        {% else %}
        <div class="card_text" data-like="ture"  style="color:black; height: 16px;"  data-id="{{movie.id}}"> ♡ </div>
        <span id = "like-count-{{movie.id}}" >{{ movie.like_users.count }}</span>
        {% endif %}
        <div style="font-size: 14px;">
          장르:
          {% for genre in movie.genres.all %}
          {% if forloop.counter < 4 %}
            {{ genre.name }}
          {% endif %}
          {% endfor %}
        </div>
      </div>
  </div>
</div>
{% endfor %}

<div class="col-sm-6 col-md-4"></div>
<div class="col-sm-6 col-md-4"></div>
<script>  
  const likeBtns = document.querySelectorAll('[data-like]')
  
  likeBtns.forEach((likeBtn)=>{
    likeBtn.addEventListener('click',function(event){
      const movieId = event.target.dataset.id
      const movieLikeCount = document.querySelector(`#like-count-${movieId}`)

      axios.get(`/movies/${movieId}/like/`)
      .then((response)=>{
        console.log(response.data)
        if (response.data.status){
          event.target.innerText = '♥'
          event.target.style.color = "crimson"
          movieLikeCount.innerHTML = response.data.like_count

        } else{
          event.target.innerText = '♡'
          event.target.style.color = "black"
          movieLikeCount.innerHTML = response.data.like_count
        }
      }
      )
    })
  })  
  </script>
{% endblock %}

django_pjt5/movies/templates/movies/recommand_random.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}

{% block body %}
  <div class="text-center h1 col-6 mt-5 mb-5" style="border-bottom: 2px solid">영화 추천 게시판</div>
  <div class="col-12"></div>
  {% for movie in movies %}

  <div class="col-sm-6 col-md-4 mb-3" style="">
    <div class="border mx-2 p-3">
        <img src="https://image.tmdb.org/t/p/w780/{{movie.poster_path}}" class="card-img-top p-1" width = "auto" height="400px">
        <div class="card-body" >
          <h6 class="card_text">{{movie.title}} </h6>
          <hr>
          <div class ="col-5  offset-7">평점 : {{ movie.vote_average }}</div>
          <div class="card-text"  ><p style="overflow: hidden;
          text-overflow: ellipsis;
          display:-webkit-box;
          -webkit-box-orient: vertical;
          -webkit-line-clamp: 5;
          word-wrap: break-word;
          line-height: 1.2em;
          height: 6em;

            ">{{movie.overview}}</p></div>
          <hr>
          {% if request.user in movie.like_users.all %}
          <div class="card_text" data-like="true" style="color:crimson; height: 16px;" data-id="{{movie.id}}"> ♥</div>
          <span id = "like-count-{{movie.id}}" >{{ movie.like_users.count }}</span>
          {% else %}
          <div class="card_text" data-like="ture"  style="color:black; height: 16px;"  data-id="{{movie.id}}"> ♡ </div>
          <span id = "like-count-{{movie.id}}" >{{ movie.like_users.count }}</span>
          {% endif %}
          <div style="font-size: 14px;">
            장르:
            {% for genre in movie.genres.all %}
            {% if forloop.counter < 4 %}
              {{ genre.name }}
            {% endif %}
            {% endfor %}
          </div>
        </div>
    </div>
  </div>
  {% endfor %}
  <div class="col-sm-6 col-md-4"></div>
  <div class="col-sm-6 col-md-4"></div>
  <div class= "w-100"></div>



  <script>  
  const likeBtns = document.querySelectorAll('[data-like]')
  
  likeBtns.forEach((likeBtn)=>{
    likeBtn.addEventListener('click',function(event){
      const movieId = event.target.dataset.id
      const movieLikeCount = document.querySelector(`#like-count-${movieId}`)

      axios.get(`/movies/${movieId}/like/`)
      .then((response)=>{
        console.log(response.data)
        if (response.data.status){
          event.target.innerText = '♥'
          event.target.style.color = "crimson"
          movieLikeCount.innerHTML = response.data.like_count

        } else{
          event.target.innerText = '♡'
          event.target.style.color = "black"
          movieLikeCount.innerHTML = response.data.like_count
          

        }


      }

      )







    })





  })
  
  
  
  
  </script>
{% endblock %}